import type { Metadata } from "next";

import "./globals.css";

// provider
import TanstackProvider from "@/providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Tanstack Query",
  description: "Generated by addispic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
